In [16]:
import pandas as pd
import numpy as np
m1 = pd.DataFrame(np.random.randint(0, 5,size=(3,3)))
m2 = pd.DataFrame(np.random.randint(0, 5,size=(3,3)))

In [7]:
print (m1)
m2

   0  1  2
0  1  2  0
1  3  1  4
2  4  3  0


0  1  2
0  1  2  3
1  0  0  2
2  4  0  2

## """matrix multification"""

In [9]:
m3=m1.dot(m2)##dot是典型的dot multification，
m3
##第一行 1x1+2x0+0x4=1; 1x2+2x0+0x0=2; 1x3+2x2+0x2=7;
##第二行 3x1+1x0+4x4=19; 3x2+1x0+4x0=6;3x3+1x2+4x2=19;
##.......

0  1   2
0   1  2   7
1  19  6  19
2   4  8  18

In [11]:
##除了dot其他都是elementwise function
m4=m1.multiply(m2)
m4

0  1  2
0   1  4  0
1   0  0  8
2  16  0  0

In [10]:
mm4= m1.add(m2)
mm4

0  1  2
0  2  4  3
1  3  1  6
2  8  3  2

## """function to elements/series(lists)"""

In [20]:
m4.apply(lambda x:sum(x))

0    17
1     4
2     8
dtype: int64

In [21]:
m4.applymap(lambda x:x**2)

0   1   2
0    1  16   0
1    0   0  64
2  256   0   0

In [26]:
l=[1,2,3,4]
print (list(map(lambda x:x**2,l))) # built in fucntion map syntax: r = map(func, seq)
print (list(filter(lambda x:x**2<6,l)))   

#def(x)=x**2
g=lambda x:x**2
print (g(2))

[1, 4, 9, 16]
[1, 2]
4


## vectorization dot

In [29]:
a1 = pd.DataFrame(np.random.randint(0, 5,size=(3,3)))
a2 = pd.DataFrame(np.random.randint(0, 5,size=(3,3)))

In [36]:
a3=np.array([[1,3,5]])

In [37]:
np.dot(a1,a3)###这个出错了，shape（a,b)必须乘以（b,n)n大于等于1。。。

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [40]:
a4=a3.reshape(3,1)
a4

array([[1],
       [3],
       [5]])

In [42]:
np.dot(a1,a4)

array([[30],
       [ 3],
       [21]])

#### outer vectorization

In [49]:
x1 = [9, 2, 5, 0]
x2 = [9, 2, 2, 9]

In [51]:
np.outer(x1,x2)###outer 就是用x1全部乘以x2的每一个item

array([[81, 18, 18, 81],
       [18,  4,  4, 18],
       [45, 10, 10, 45],
       [ 0,  0,  0,  0]])